### ISSUE TITLE
Sign Up / Login

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#1]
Users must log in by providing their username and password. Log in can be mock.

When logged in, the user's name must be shown in the navigation drawer. When not logged in, a "Welcome" message should be shown instead.

- [x] Create Log in screen

- [x] Include Login icon inside Navigation Drawer / show user Name

- [x] Include Logout icon inside Navigation Drawer / show Welcome message

- [x] Mock screen - no functionalities

- [x] Styling

**Comment by heloysatancredo** [comment]
Nov 17 Tests - corrections to be done - DUE DATE Nov 22
- It's not on mockups, but add Link to Sign Up (Register)  below the Log in button;
- It's not on mockups, but if the user wants to cancel the activity of Logging in to add a review and just want to go back to the menu there's no option (user has to start the process from the beginning - search restaurants, etc...)
