### ISSUE TITLE
Navigation Drawer

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#14]
### Wireframe/Mockup
https://xd.adobe.com/view/8aa92799-3e49-4aab-5778-ece3fbab42c1-fc98/screen/2f31ed5e-c9a7-4b39-b21a-17fd194b64bf/Menu

### Description
User must see navigation drawer with the options: 1) Select Restaurant (sub-options: QR Code / Search by name),  2) Log in / Log out (can be icons). When selecting QR Code, redirects to Home screen. When selecting Search by name option, redirects to Seach screen.

At the top, the navigation drawer must show the user's Name (if logged in) or "Welcome" message (if not logged in).

### Tasks

- [x] Create side drawer
- [x] Create links with proper redirects

**Comment by heloysatancredo** [comment]
Nov 17 Tests - Corrections to be done - DUE DATE Nov 22
- Remove avatar image
- Missing style

**Comment by wbgneto** [comment]
@jyotSarup please fix style
