### ISSUE TITLE
QR Code Scan

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#2]
(Also known as Home screen)

Users must see a QR reader option (e.g. button) that, when clicked, will open the camera to read the QR code. After reading the QR, users will be redirected to the restaurant's menu. 

In addition, on the Home screen, users must also see an option (e.g. link) that will redirect to a Search screen (search restaurant by name). 

From this screen on, side menu is available to the users.

- [x] Create Home page 

- [x] Create QR code option 

- [x] Create Search option

- [x]  When selecting QR Code, the camera must open to read QR. After reading, users are directed to the restaurant's menu (QR refers to the restaurant's identification)

- [x] When selecting Search, redirect to the Search screen

- [x] Enable side menu functionality

- [x] Styling

**Comment by heloysatancredo** [comment]
Nov 17 Tests
Tested just in the browser.
No corrections to be done detected. Necessary to test QR READER ON MOBILE.
