### ISSUE TITLE
Menu - Dishes List

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#4]
Users must see the whole Menu of the restaurant. At the top, users must see the featured dishes (e.g slide) that shows name, photo and rating of the dish. When clicking on a featured dish, users must be redirected to the Dish Details screen.

At the top, users must also see the categories of the menu, being able to select a specific category (e.g. horizontal scroll). When selecting a category, the screen must automatically scroll directly to the category position inside the menu.

In addition, users can see a filter option (e.g. button) to filter items by characteristics (e.g. radio) and categories (e.g dropdown). 

Each item in the menu must show Name, Short description (2 lines), price,  main image, rating and tags (colorful). Users can select an item to see more details. After selecting an item, users are directed to the Details screen.

- [x] Create Menu screen

- [x] Create featured dishes functionality (slide)

- [x] Create categories view and selection functionality (horizontal scroll)

- [x] Create filter functionality - filter must incude characteristcs (tags) and categories

- [x] When users select an item, redirect to Details screen

- [ ] Styling

**Comment by heloysatancredo** [comment]
Nov 17 tests - corrections to be done - DUE DATE Nov 22:
- The short description should display just 2 lines and ...
- Margins top and bottom are too big for each dish (need to reduce space before and after)
- Missing styling

**Comment by heloysatancredo** [comment]
[ ] - Fix thumbnails images
