### ISSUE TITLE
Dish Details

### ISSUE THREAD

**Issue by waltergalvao** [waltergalvao/dishlist.mobile#6]
### Description

Screen to show details about a dish.

Our screen will look like TripAdvisor

The screen will have 3 top fixed tabs, which scrolls to the appropriate height. The content is actually linear, so you can scroll by yourself.

[Main Photo]  
[Price][Time][Tags]  
-- Overview -- Reviews -- User Photos  
[Dish Name]  
[Description]  
[Ingredients]  
-- (Reviews Tab)
[Average Rating]
[Review 1]
[Review 2]
[Review 3]
[Show More Button]
-- (User Photos Tab)
[PhotoGrid]
[Show More Button]
  
  
There should also be a Create Review button. The location of the button is still not decided.

**Comment by heloysatancredo** [comment]
Nov 17 corrections - DUE DATE Nov 22:
- Price / Time / People served are not properly aligned
- Rating (on the dish's image) needs a bit more contrast (maybe make it bold, a bit bigger)
- Define alignment as left for the characteristics(Vegan, etc), to start at the same point of description
- Missing final style

**Comment by heloysatancredo** [comment]
REVIEWS tab
Nov 17 corrections - DUE DATE Nov 22:
- Missing style

**Comment by heloysatancredo** [comment]
PHOTOS tab
Nov 17 corrections - DUE DATE Nov 22:
- Style (when selecting the tab its title should change color to red, according to mockups)
